
CREATE TABLE order_details
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id BIGINT,
    quantity   INT,
    price      DOUBLE PRECISION,
    order_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_details PRIMARY KEY (id)
);

ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDER_DETAILS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);